  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  EKSSecurityGroupExport:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS Cluster Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub DevOps-SecurityGroup-${Environment}

Outputs:
  VPCId:
    Value: !Ref VPC
    Export:
      Name: !Sub DevOps-VPC-${Environment}-Id

  PublicSubnet1:
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub DevOps-Subnet1-${Environment}-Id

  PublicSubnet2:
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub DevOps-Subnet2-${Environment}-Id

  EKSSecurityGroup:
    Value: !Ref EKSSecurityGroup
    Export:
      Name: !Sub DevOps-SecurityGroup-${Environment}-Id
